CREATE TABLE IF NOT EXISTS tax_rule (
  id bigint generated by default as identity,
  income_start integer,
  income_end integer,
  tax_on_each_dollar decimal(21, 3),
  slab_addition integer,
  is_active boolean,
  primary key (id)
);